name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: install packages
      run: sudo sed -i 's/main$/main non-free/' /etc/apt/sources.list && sudo apt-get update && sudo apt-get install --no-install-recommends -y git build-essential qt5-qmake qtbase5-dev ca-certificates
    - name: cleanup and revert list
      run: sudo rm -rf /var/lib/apt/lists/*
    - name: ls
      run: ls .
    - name: make and compile src
      run: cd src && qmake -o Makefile nzbCheck.pro && make -j$(nproc)
