name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: install packages
      run: sed -i 's/main$/main non-free/' /etc/apt/sources.list && apt-get update && apt-get install --no-install-recommends -y git build-essential qt5-qmake qtbase5-dev ca-certificates
    - name: cleanup and revert list
      run: rm -rf /var/lib/apt/lists/*
    - name: make and compile
      run: qmake -o Makefile ngPost.pro && make -j$(nproc)
    - name: make and compile src
      run: cd /usr/src/nzbCheck/src && qmake -o Makefile nzbCheck.pro && make -j$(nproc)
