name: ngPost CLI x64

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  version: '4.16.1'

jobs:
  build_linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: install packages
      run: sudo sed -i 's/main$/main non-free/' /etc/apt/sources.list && sudo apt-get update && sudo apt-get install --no-install-recommends -y git build-essential qt5-qmake qtbase5-dev ca-certificates
    - name: cleanup and revert list
      run: sudo rm -rf /var/lib/apt/lists/*
    - name: ls
      run: ls .
    - name: make and compile src
      run: cd src && qmake -o Makefile ngPost_cmd.pro && make -j$(nproc)
    - name: list src
      run: ls -alt src/ && realpath src
    - name: Create Release
      id: linux_create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: linux-${{ env.version }}
        release_name: Release Linux x64 ${{ env.version }}
        draft: false
        prerelease: false
    - name: Upload ngpost
      id: upload-release-asset-ngpost
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.linux_create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
        asset_path: ${{ github.workspace }}/src/ngPost
        asset_name: ngpost_linux_v${{ env.version }}
        asset_content_type: application/octet-stream

  build_windows:
    runs-on: windows-2019
    needs: [build_linux]
    
    env:
      SOURCE_DIR:   ${{ github.workspace }}
      QT_VERSION:   5.15.2
      ARTIFACT:     ngPost_cmd.zip

    steps:
    - uses: actions/checkout@v3
    
    - name: install qt
      uses: jurplel/install-qt-action@v3.3.0
      with:
        version:      ${{ env.QT_VERSION }}
        host:         windows
        target:       desktop
        arch:         win64_msvc2019_64
        dir:          ${{ runner.temp }}
        
    - name: download JOM
      uses: suisei-cn/actions-download-file@v1
      with:
          url:    http://download.qt.io/official_releases/jom/jom.zip
          target: ${{ runner.temp }}\
    - name: unzip jom
      working-directory: ${{ runner.temp }}
      run:  |
            7z x jom.zip -ojom

    - name: Create build directory
      run:  mkdir ${{ runner.temp }}\build

    - name: Set up Visual Studio shell
      uses: egor-tensin/vs-shell@v2
      with:
          arch: x64

    - name: Build
      working-directory: ${{ runner.temp }}\build
      run:  |
            qmake -r ${{ env.SOURCE_DIR }}\src\ngPost_cmd.pro
            ${{ runner.temp }}\jom\jom -j2
            cd release
            windeployqt --qmldir ${{ env.SOURCE_DIR }} ngPost.exe --pdb --release --compiler-runtime
            copy C:\Windows\System32\concrt140.dll . 
            copy C:\Windows\System32\vccorlib140.dll .
            copy C:\Windows\System32\msvcp140.dll .
            copy C:\Windows\System32\vcruntime140.dll .
            copy ${{ env.SOURCE_DIR }}\ngPost.conf

    - name: Zip build
      working-directory: ${{ runner.temp }}
      run:  |
            7z a ngPost_cmd.zip ${{ runner.temp }}\build\* -r -xr!*.cpp -xr!*.h -xr!*.obj

    - name: Create Release
      id: win_create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: win-${{ env.version }}
        release_name: Release Windows x64 ${{ env.version }}
        draft: false
        prerelease: false

    - name: Upload ngpost
      id: upload-release-asset-ngpost
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.win_create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
        asset_path: ${{ runner.temp }}\${{ env.ARTIFACT }}
        asset_name: ngpost_windows_v${{ env.version }}.zip
        asset_content_type: application/zip
